"""add live transcript column

Revision ID: 04da70b79ac2
Revises: 1f18e2b74316
Create Date: 2026-05-04 10:31:11.434240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04da70b79ac2'
down_revision: Union[str, Sequence[str], None] = '1f18e2b74316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('transcript', sa.Text(), nullable=True))
    op.drop_column('meetings', 'auto_join')
    op.drop_column('meetings', 'scheduled_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('meetings', sa.Column('auto_join', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('meetings', 'transcript')
    # ### end Alembic commands ###
