"""add google fields

Revision ID: 13a648ee7e93
Revises: 27b4318ca261
Create Date: 2026-05-01 11:12:56.201280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a648ee7e93'
down_revision: Union[str, Sequence[str], None] = '27b4318ca261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('google_event_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'meetings', ['google_event_id'])
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    op.drop_constraint(None, 'meetings', type_='unique')
    op.drop_column('meetings', 'google_event_id')
    # ### end Alembic commands ###
