"""initial schema

Revision ID: 1b7cfe70c784
Revises: 
Create Date: 2026-04-29 15:11:20.283692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b7cfe70c784'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('transcript_raw', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('meetings', sa.Column('transcript_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'transcript_text')
    op.drop_column('meetings', 'transcript_raw')
    # ### end Alembic commands ###
