"""improve_schema_and_standardize_dates

Revision ID: 68376a6d3e7d
Revises: 13a648ee7e93
Create Date: 2026-05-01 12:55:25.491999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68376a6d3e7d'
down_revision: Union[str, Sequence[str], None] = '13a648ee7e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('meetings', 'meeting_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('participants', sa.Column('is_organizer', sa.String(), nullable=True))
    op.add_column('participants', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('participants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('participants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('tasks', sa.Column('is_completed', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'task',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="CASE WHEN due_date ~ '^\\d{4}-\\d{2}-\\d{2}' THEN due_date::timestamp ELSE NULL END")
    op.add_column('users', sa.Column('google_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('google_profile_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'google_profile_picture')
    op.drop_column('users', 'google_profile_name')
    op.drop_column('users', 'google_token_expires_at')
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tasks', 'task',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'is_completed')
    op.alter_column('participants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('participants', 'created_at')
    op.drop_column('participants', 'avatar_url')
    op.drop_column('participants', 'is_organizer')
    op.alter_column('meetings', 'meeting_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('meetings', 'updated_at')
    # ### end Alembic commands ###
