"""add_scheduled_at_and_auto_join

Revision ID: dc687fee8a00
Revises: 6b4a9ae3c55e
Create Date: 2026-05-01 15:20:39.997420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc687fee8a00'
down_revision: Union[str, Sequence[str], None] = '6b4a9ae3c55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('auto_join', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'auto_join')
    op.drop_column('meetings', 'scheduled_at')
    # ### end Alembic commands ###
