"""add recall_id to participant

Revision ID: fdebe2e3db80
Revises: 6b4a9ae3c55e
Create Date: 2026-05-03 22:57:52.046892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdebe2e3db80'
down_revision: Union[str, Sequence[str], None] = '6b4a9ae3c55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('recall_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'recall_id')
    # ### end Alembic commands ###
